# Generated by Django 4.2.4 on 2023-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='social_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='social_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='social_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='social_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
